# This config file defines the base approach to training a Wasserstein Bi-GAN
name: wbigan

models: # Define model parameters
  z_dim: 128 # Latent vector dimension
  num_classes: 37 # The number of conditional class IDs

training: # Specify parameters used for training
  batch_size: 256
  critic_updates: 1 # The number of updates to the discriminator for every update to G and E
  lambda_val: 20.0 # Controls the gradient penalty to proxy 1-Lipschitz condition
  lr: 1.0e-4  # 5.5e-5
  weight_decay: 0.0e-0
  pretrain_num_steps: 100000
  train_num_steps: 300000
  adam_betas: [0.9, 0.999]
  grad_clip: 3.0
  use_amp: True
  use_latest_checkpoint: True
  eval_every: 1000
  save_every: 10000
