# This config file the config for training a Wasserstein Bi-GAN on the CelebA dataset
name: celebA_wigan
dataset: celebA

models: # Define model parameters
  z_dim: 64 # Latent vector dimension
  image_dim: 64 # The size of the images going in and out of the models i.e. [image_dim, image_dim, 3]
  num_classes: 2 # The number of conditional class IDs

pretraining: # Specify parameters used for pretraining
  batch_size: 128
  lr: 1.0e-4
  weight_decay: 1.0e-5
  num_steps: 10000
  adam_betas: [ 0.9, 0.999 ]
  grad_clip: 1.0
  use_amp: True
  use_latest_checkpoint: True
  eval_every: 500
  save_every: 2000

training: # Specify parameters used for training
  batch_size: 256
  lr: 1.0e-4 # 1.0e-4  # 5.5e-5
  weight_decay: 0.0e-0
  num_steps: 50000
  adam_betas: [ 0.5, 0.9 ]
  grad_clip: 100.0
  use_amp: True
  use_latest_checkpoint: True
  eval_every: 500
  save_every: 500
  critic_updates: 5 # The number of updates to the discriminator for every update to G and E
  lambda_val: 10.0 # Controls the gradient penalty to proxy 1-Lipschitz condition
